FROM quay.io/toolbx/arch-toolbox:latest

RUN pacman-key --init \
	&& pacman -Sy \
	&& pacman -S --noconfirm archlinux-keyring dbus base-devel systemd cmake libvterm openssh git emacs-wayland vim chromium firefox htop tmux docker kitty stow mpv intel-media-driver libva-utils intel-gpu-tools gwenview python nodejs npm okular unrar unzip dolphin kio-admin konsole kdegraphics-thumbnailers kde-cli-tools ffmpegthumbs


